name: if-expressions
run-name: Expressão IF

on:
    - push
    - pull_request

jobs:
    if-expression:
        runs-on: ubuntu-latest
        steps:
            - name: Only on push
              if: github.event_name == 'push'
              run: echo 'Foi feito um push!'
            
            - name: Only on PR
              if: github.event_name == 'pull_request'
              run: echo 'Foi feita uma PR!'

            # - name: Failure
            #   run: doesnotexists

            - name: Echo string
              run: echo 'Olá GitHub Actions'
            
            - name: Execute on failure
              if: failure()
              run: echo 'O workflow falhou'
